In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\USER\Desktop\5th sem\project1_daibatise\data\processed\project1_diabetes_clean.csv",parse_dates=["last_checkup_date"])

In [3]:
df.head(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unkown,NO,2023-04-20,0
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKOWN,2023-07-08,0
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unkown,YES,2024-04-14,1
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0
5,P00755,37,female,0,145.0,80.0,26.0,124.0,22.0,0.488,High,YES,2024-01-10,0
6,P00431,58,male,5,95.0,72.0,26.0,170.0,27.2,0.197,High,NO,2023-12-25,0
7,P00542,58,female,3,150.0,68.0,17.0,124.0,46.0,0.808,Medium,NO,2024-06-20,1
8,P00929,32,female,6,129.0,74.0,26.0,226.0,20.6,0.655,High,UNKOWN,2023-10-15,1
9,P00513,61,female,0,161.0,77.0,35.0,201.0,35.0,1.229,Medium,YES,2023-12-22,1

In [4]:
df.dtypes

patient_id                      str
age                           int64
gender                          str
pregnancies                   int64
glucose                     float64
blood_pressure              float64
skin_thickness              float64
insulin                     float64
bmi                         float64
diabetes_pedigree           float64
physical_activity               str
smoker                          str
last_checkup_date    datetime64[us]
outcome                       int64
dtype: object

In [5]:
df.shape

(950, 14)

create an age -band feature

In [6]:
df['age_band'] = pd.cut(
    df['age'],bins=[0,35, 55,120] ,labels=("youth","middle_aged","senior")
)

In [7]:
df.head()

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome,age_band
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unkown,NO,2023-04-20,0,senior
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1,middle_aged
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKOWN,2023-07-08,0,middle_aged
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unkown,YES,2024-04-14,1,senior
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0,senior

create bmi category feautre

In [8]:
df["bmi_category"] = pd.cut(
    df['bmi'], bins=[0,18.5,25,30,100],
labels=["underweight","normal","overweight","obese"])

In [9]:
df.head(20)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome,age_band,bmi_category
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unkown,NO,2023-04-20,0,senior,normal
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1,middle_aged,obese
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKOWN,2023-07-08,0,middle_aged,overweight
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unkown,YES,2024-04-14,1,senior,overweight
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0,senior,normal
5,P00755,37,female,0,145.0,80.0,26.0,124.0,22.0,0.488,High,YES,2024-01-10,0,middle_aged,normal
6,P00431,58,male,5,95.0,72.0,26.0,170.0,27.2,0.197,High,NO,2023-12-25,0,senior,overweight
7,P00542,58,female,3,150.0,68.0,17.0,124.0,46.0,0.808,Medium,NO,2024-06-20,1,senior,obese
8,P00929,32,female,6,129.0,74.0,26.0,226.0,20.6,0.655,High,UNKOWN,2023-10-15,1,youth,normal
9,P00513,61,female,0,161.0,77.0,35.0,201.0,35.0,1.229,Medium,YES,2023-12-22,1,senior,obese
10,P00300,61,female,0,90.0,70.0,14.0,10.0,31.1,0.050,Low,NO,2023-02-19,0,senior,obese
11,P00106,41,male,0,102.0,66.0,32.0,110.0,40.3,0.312,High,YES,2023-04-06,0,middle_aged,obese
12,P00061,68,male,0,82.0,63.0,20.0,10.0,33.7,0.191,Medium,NO,2024-08-18,0,senior,obese
13,P00628,52,female,0,144.0,84.0,7.0,203.0,31.9,0.315,Medium,UNKOWN,2024-07-28,1,middle_aged,obese
14,P00462,31,female,0,100.0,72.0,35.0,121.0,27.2,0.498,Unkown,UNKOWN,2023-01-14,0,youth,overweight
15,P00149,24,female,0,167.0,75.0,26.0,124.0,49.0,0.231,Low,UNKOWN,2024-05-18,0,youth,obese
16,P00215,61,male,0,134.0,72.0,33.0,126.0,28.7,0.432,Medium,YES,2024-10-19,0,senior,overweight
17,P00165,38,male,0,89.0,79.0,19.0,124.0,30.0,0.054,Medium,YES,2023-07-03,0,middle_aged,overweight
18,P00238,52,female,0,139.0,71.0,19.0,124.0,34.7,0.280,Medium,NO,2023-06-10,0,middle_aged,obese
19,P00026,27,female,2,91.0,68.0,29.0,180.0,31.1,0.825,Medium,NO,2023-07-24,0,youth,obese

In [10]:
df['bmi_category'].value_counts()

bmi_category
obese          553
overweight     235
normal         124
underweight     38
Name: count, dtype: int64

check the glucose band distribution

In [11]:
df["glucose_band"] = pd.cut(
    df['glucose'], bins=[0,100,126,300,],
labels=["normal","prediabetic","diabetic"])

In [12]:
df.head()

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome,age_band,bmi_category,glucose_band
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unkown,NO,2023-04-20,0,senior,normal,prediabetic
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1,middle_aged,obese,diabetic
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKOWN,2023-07-08,0,middle_aged,overweight,diabetic
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unkown,YES,2024-04-14,1,senior,overweight,prediabetic
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0,senior,normal,prediabetic

In [13]:
df['glucose_band'].value_counts()

glucose_band
diabetic       349
prediabetic    337
normal         264
Name: count, dtype: int64

In [14]:
df['insulin_glucose_ratio']=df['insulin']/df['glucose']

In [15]:
df['insulin_glucose_ratio'].head(10)

0    1.000000
1    0.274510
2    1.119718
3    1.024793
4    0.943925
5    0.855172
6    1.789474
7    0.826667
8    1.751938
9    1.248447
Name: insulin_glucose_ratio, dtype: float64

check the ratio for impossible value

In [17]:
df['insulin_glucose_ratio'].describe()

count    950.000000
mean       1.213108
std        1.179183
min        0.054348
25%        0.726708
50%        1.052139
75%        1.512831
max       22.745763
Name: insulin_glucose_ratio, dtype: float64

In [18]:
import numpy as np

In [20]:
np.isinf(df['insulin_glucose_ratio']).sum()

np.int64(0)

create a pregnancies-pe-year-of-age feature

In [21]:
df['pregnancy_rate']=df['pregnancies']/df['age']

In [22]:
np.isinf(df['pregnancy_rate']).sum()

np.int64(0)

In [23]:
df['pregnancy_rate'].describe()

count    950.000000
mean       0.042787
std        0.067440
min        0.000000
25%        0.000000
50%        0.000000
75%        0.072661
max        0.380952
Name: pregnancy_rate, dtype: float64

create a days since last checkup feature

In [25]:
reference_date=df['last_checkup_date'].max()
reference_date

Timestamp('2024-12-28 00:00:00')

create a categorical combination feature

In [26]:
df['since_checkup'] = (reference_date-df['last_checkup_date']).dt.days

In [27]:
df['since_checkup'].head()

0    618
1    239
2    539
3    258
4    336
Name: since_checkup, dtype: int64

check the    combination feature balance

In [29]:
df['activity_smoker'] = df['physical_activity'] +"/" + df["smoker"]

In [31]:
df['activity_smoker'].value_counts()

activity_smoker
Medium/NO        207
High/NO          195
Low/NO           180
Low/YES           93
Medium/YES        90
High/YES          85
Unkown/NO         36
High/UNKOWN       22
Unkown/YES        17
Medium/UNKOWN     12
Low/UNKOWN         9
Unkown/UNKOWN      4
Name: count, dtype: int64

inventory every new columns

In [32]:
# activity smoker = physical activity + smoker
# since_checkup = reference- last_checkup_date
# pregence_rate = pregnency/age
# insulin_glucose = insulin/glucose
# glucose_band = glucose
# bmi_category=bmi
# age_band=age

In [34]:
df.shape

(950, 21)